# Generated by Django 4.1.6 on 2023-02-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='Human first name')),
                ('lname', models.CharField(max_length=50, verbose_name='Human last name')),
                ('age', models.IntegerField(verbose_name='Human age')),
            ],
        ),
    ]
